version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: boot-lover-db
    restart: always
    environment:
      POSTGRES_USER: bootlover_user
      POSTGRES_PASSWORD: senhaSegura123
      POSTGRES_DB: bootlover_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

